# ***ANALYZING THE SAMPLES DATASET***

**USING THE FOLLOWING LIBS**

In [1]:
import pandas as pd

**READING THE FOLLOWING FILES**

In [ ]:
#Extrair e analisar dados -> Passar por LLM pra augmentation -> limpeza -> encoding -> modelos

In [ ]:
smaller_dataset = pd.read_csv('data/raw/mbti_1.csv')
bigger_dataset = pd.read_csv('data/raw/mbti_full_pull.csv')

In [7]:
smaller_dataset.shape

(8675, 2)

In [8]:
smaller_dataset.head(10)

   type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...
5  INTJ  '18/37 @.@|||Science  is not perfect. No scien...
6  INFJ  'No, I can't draw on my own nails (haha). Thos...
7  INTJ  'I tend to build up a collection of things on ...
8  INFJ  I'm not sure, that's a good question. The dist...
9  INTP  'https://www.youtube.com/watch?v=w8-egj0y8Qs||...

In [10]:
smaller_dataset['posts'].iloc[1]

"'I'm finding the lack of me in these posts very alarming.|||Sex can be boring if it's in the same position often. For example me and my girlfriend are currently in an environment where we have to creatively use cowgirl and missionary. There isn't enough...|||Giving new meaning to 'Game' theory.|||Hello *ENTP Grin*  That's all it takes. Than we converse and they do most of the flirting while I acknowledge their presence and return their words with smooth wordplay and more cheeky grins.|||This + Lack of Balance and Hand Eye Coordination.|||Real IQ test I score 127. Internet IQ tests are funny. I score 140s or higher.  Now, like the former responses of this thread I will mention that I don't believe in the IQ test. Before you banish...|||You know you're an ENTP when you vanish from a site for a year and a half, return, and find people are still commenting on your posts and liking your ideas/thoughts. You know you're an ENTP when you...|||http://img188.imageshack.us/img188/6422/6020d1f9da6944a6b71bbe6.jpg|||http://img.adultdvdtalk.com/813a0c6243814cab84c51|||I over think things sometimes. I go by the old Sherlock Holmes quote.  Perhaps, when a man has special knowledge and special powers like my  own, it rather encourages him to seek a complex...|||cheshirewolf.tumblr.com  So is I :D|||400,000+  post|||Not really; I've never thought of E/I or J/P as real functions.  I judge myself on what I use. I use Ne and Ti as my dominates. Fe for emotions and rarely Si. I also use Ni due to me strength...|||You know though. That was ingenious. After saying it I really want to try it and see what happens with me playing a first person shooter in the back while we drive around. I want to see the look on...|||out of all of them the rock paper one is the best. It makes me lol.  You guys are lucky :D I'm really high up on the tumblr system.|||So did you hear about that new first person shooter game? I've been rocking the hell out of the soundtrack on my auto sound equipment that will shake the heavens. We managed to put a couple PS3's in...|||No; The way he connected things was very Ne. Ne dominates are just as aware of their environments as Se dominates.  Example: Shawn Spencer or Patrick Jane; Both ENTPs.|||Well charlie I will be the first to admit I do get jealous like you do. I chalk it up to my 4w3 heart mixed with my dominate 7w8. 7s and 8s both like to be noticed. 4's like to be known (not the same...|||;D I'll upload the same clip with the mic away from my mouth. Than you won't hear anything.  Ninja Assassin style but with splatter.|||Tik Tok is a really great song. As long as you can mental block out the singer. I love the beat it makes me bounce.|||drop.io v1swck0  :D Mic really close to my mouth and smokin aces: assassins ball playing in the background.|||Sociable =/= extrovert; I'm an extrovert and I'm not sociable. :)|||Sherlock in the movie was an ENTP. Normally he's played as a EXTJ. In the books he's an ESTJ.  As I said. The movie looked good except for it being called sherlock holmes.|||http://i817.photobucket.com/albums/zz96/kamioo/Dirtywinch.png|||Oh, I never had fear of kissing a guy. I will kiss an animal too. So there was nothing to vanish. Just personal taste and me not liking it.  The guy I kissed didn't know me. It was one of those...|||Sounds pretty much like my area and what I'm going through right now trying to figure out which way I want to take my life. I want to do so many things. The biggest problem is that I know if I don't...|||;D I was operating under the impression that you were female. I never looked at your boxy. Okay, I help out my gay friends all the time and one of them has developed a little crush on me. I get red...|||T_T You just described me  and I'm living the worst nightmare. I'm trapped in one place with one one around. Only dull woods. If I was a serial killer this would be the perfect place but sadly I'm...|||TBH, and biased, sounds like a shadowed INFP. I think maybe he was hurt and turned ESTJ. I can tell because he has some of the typical INFP traits left over.|||*Checks list* I'm sorry. It seems that you have came at a bad time. We've already reached our quota of INFJs. However, being you're female and I like females I will make you a deal. I will kick one...|||I'm ANTP (Leaning toward E). I'm easy for both ENTPs and INTPs to identify with. :)|||I also imagine ENTP's interrogations would go a little bit like Jack's from 24 except more mechanical. Rigging up shock treatment equipment in an abandoned building out of an old car batty, jumper...|||It was a compliment :) Trust me. I'm just as psychopathic :D except I have emoticons. They're just weird ones. Like laughing when I get hurt or at people running themselves over with their lawn mower...|||http://i817.photobucket.com/albums/zz96/kamioo/Thunderstorm.pnghttp://i817.photobucket.com/albums/zz96/kamioo/Thunderstormbw.png http://i817.photobucket.com/albums/zz96/kamioo/Cosmicstorm.png|||No. It's like a theme for where I live and that is why I know it by heart.   http://www.youtube.com/watch?v=j5W73HaVQBg|||and I usual don't leave until the thing ends. But in the mean time. In between times. You work your thing. I'll work mine :D  ;D I'm the MBP; Pleasure to meet you.|||Damn, need to trust my instincts more I would have been closer I was going to say INFP.|||EXFP? Leaning toward S with the way she responded.  :D My friends, even my gay and lesbian ones, always come to me for advice.|||I bow to my entp masters ENTPs are so great. If it wasn't for ENTPs I wouldn't have been able to build what I'm building  Duck Duck  Duck  Shotgun|||What? Me? I never do that >.> <.<|||Because its hard to be sad about losing someone you like when you knew you were right and give yourself a big pat on the back because you're awesome and always correct.|||Oh, you don't have to tell me that most of them are stupid. I know this. That is why I play with them and it makes me laugh. :D As I'm going to take Neuropsychology and I have a few psychologist...|||:D I'm a Nightowl. I wake up between 6-7pm and stay awake till 10-11:30am.|||Personal opinion backed by theory would suggest that INTPs are the most socially difficult. While INTJs can be socially indifferent but they will also use social situations if the the need arises....|||Personal stocks that I have on my desktop that I've downloaded from random stock sites and stock photobuckets.|||I'll tell you when I open photoshop.  :) Glad you like it static.|||:D Thanks.|||http://i817.photobucket.com/albums/zz96/kamioo/Deathgrip.png http://i817.photobucket.com/albums/zz96/kamioo/Deathgripbw.png  Made for a friend. Several hours of work. I constructed every line by...|||:) Static: http://i817.photobucket.com/albums/zz96/kamioo/Statickitten.png  I'll have to get to your avatar later if one of my fellow teammates doesn't.|||Psychologist don't keep me around long enough to diagnosis me. I like to toy with them. What I have diagnosis myself with and had a few psychologist friends (+ a few other friends) tell me I have is...'"

In [13]:
smaller_dataset['type'].value_counts()

type
INFP    1832
INFJ    1470
INTP    1304
INTJ    1091
ENTP     685
ENFP     675
ISTP     337
ISFP     271
ENTJ     231
ISTJ     205
ENFJ     190
ISFJ     166
ESTP      89
ESFP      48
ESFJ      42
ESTJ      39
Name: count, dtype: int64

In [11]:
bigger_dataset.head()

,author_flair_text,body,subreddit
0,INTJ,Knowing you're in INTJ is a tool for you to us...,intj
1,INTJ,You are truly an enlightened mastermind.,intj
2,"INFJ, 26F",You should :) it will help if you have a down ...,infj
3,INTP,I watch a bit of everything (including hentai)...,INTP
4,INTJ,I don't know if I would count this as a pet pe...,intj

In [15]:
bigger_dataset['author_flair_text'].value_counts()

author_flair_text
INTP                                     365646
INTJ                                     323224
ENFP                                      88334
ENTP                                      73481
INFJ                                      69730
                                          ...
[INTj-Ne 5w6] Ask me about my hobbies         1
5w6 SP | ISTP                                 1
M-20-ENTP                                     1
INFP/Leo/Hufflepuff                           1
35M INTP                                      1
Name: count, Length: 8702, dtype: int64

In [5]:
print(smaller_dataset.shape, bigger_dataset.shape)

(8675, 2) (1794016, 3)

In [6]:
smaller_dataset['type'].value_counts()

type
INFP    1832
INFJ    1470
INTP    1304
INTJ    1091
ENTP     685
ENFP     675
ISTP     337
ISFP     271
ENTJ     231
ISTJ     205
ENFJ     190
ISFJ     166
ESTP      89
ESFP      48
ESFJ      42
ESTJ      39
Name: count, dtype: int64

In [7]:
bigger_dataset['author_flair_text'].value_counts()

author_flair_text
INTP                                     365646
INTJ                                     323224
ENFP                                      88334
ENTP                                      73481
INFJ                                      69730
                                          ...
[INTj-Ne 5w6] Ask me about my hobbies         1
5w6 SP | ISTP                                 1
M-20-ENTP                                     1
INFP/Leo/Hufflepuff                           1
35M INTP                                      1
Name: count, Length: 8702, dtype: int64

In [8]:
mbti_types_list = [
    "ENFJ", "ENFP", "ENTJ", "ENTP", "ESFJ", "ESFP", "ESTJ", "ESTP",
    "INFJ", "INFP", "INTJ", "INTP", "ISFJ", "ISFP", "ISTJ", "ISTP"
]

In [9]:
def extract_mbti(txt):
    for mbti in mbti_types_list:
        if mbti in txt.upper():
            return mbti
    return 'ERROR'

In [10]:
bigger_dataset

,author_flair_text,body,subreddit
0,INTJ,Knowing you're in INTJ is a tool for you to us...,intj
1,INTJ,You are truly an enlightened mastermind.,intj
2,"INFJ, 26F",You should :) it will help if you have a down ...,infj
3,INTP,I watch a bit of everything (including hentai)...,INTP
4,INTJ,I don't know if I would count this as a pet pe...,intj
...,...,...,...
1794011,INTP,Remind me! 40 hours,INTP
1794012,INTJ,We are seeing the start of a process that is g...,intj
1794013,INTJ,[NSFDL. I cry laughing at this every single ti...,intj
1794014,INFJ,Ravenclaw!,infj
1794015,INTP,"I struggle massive with focusing, I would love...",INTP

In [11]:
bigger_dataset['mbti'] = bigger_dataset['author_flair_text'].apply(extract_mbti)

In [12]:
bigger_dataset.head()

,author_flair_text,body,subreddit,mbti
0,INTJ,Knowing you're in INTJ is a tool for you to us...,intj,INTJ
1,INTJ,You are truly an enlightened mastermind.,intj,INTJ
2,"INFJ, 26F",You should :) it will help if you have a down ...,infj,INFJ
3,INTP,I watch a bit of everything (including hentai)...,INTP,INTP
4,INTJ,I don't know if I would count this as a pet pe...,intj,INTJ

In [13]:
bigger_dataset = bigger_dataset.drop(columns = ['author_flair_text', 'subreddit'])

In [14]:
bigger_dataset.head()

                                                body  mbti
0  Knowing you're in INTJ is a tool for you to us...  INTJ
1           You are truly an enlightened mastermind.  INTJ
2  You should :) it will help if you have a down ...  INFJ
3  I watch a bit of everything (including hentai)...  INTP
4  I don't know if I would count this as a pet pe...  INTJ

In [16]:
smaller_dataset = smaller_dataset.rename(columns = {'type': 'mbti', 'posts': 'body'})

In [17]:
smaller_dataset.head()

   mbti                                               body
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [18]:
df = pd.concat([bigger_dataset, smaller_dataset], axis = 0)

In [19]:
df.head()

                                                body  mbti
0  Knowing you're in INTJ is a tool for you to us...  INTJ
1           You are truly an enlightened mastermind.  INTJ
2  You should :) it will help if you have a down ...  INFJ
3  I watch a bit of everything (including hentai)...  INTP
4  I don't know if I would count this as a pet pe...  INTJ

In [21]:
df.shape

(1802691, 2)

In [20]:
df['mbti'].value_counts()

mbti
INTP    472310
INTJ    367183
ENTP    223783
INFJ    208915
INFP    183212
ENFP     98985
ISTP     64165
ESTP     53424
ENTJ     52752
ENFJ     21810
ISTJ     18466
ISFP     11799
ISFJ      8000
ESFP      7780
ESTJ      7271
ESFJ      2836
Name: count, dtype: int64

In [22]:
df.to_csv('mbtis_labeled_dataset_1.8M.csv')